// <auto-generated />
using IsabelliDoces.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsabelliDoces.Data.Migrations
{
    [DbContext(typeof(IsabelliDocesContext))]
    partial class IsabelliDocesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("IsabelliDoces.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cep = "12345-678",
                            Complement = "Kitnet",
                            Number = "4226",
                            Street = "Rua Mato Fino",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Cep = "54321-876",
                            Complement = "",
                            Number = "9995",
                            Street = "Rua Floresta Grossa",
                            Type = 1
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Name = "Eduardo",
                            Phone = "(44) 91234-5678"
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Name = "Lana",
                            Phone = "(44) 95555-4444"
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Client", b =>
                {
                    b.HasOne("IsabelliDoces.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
