// <auto-generated />
using System;
using IsabelliDoces.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IsabelliDoces.Migrations
{
    [DbContext(typeof(IsabelliDocesContext))]
    partial class IsabelliDocesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("IsabelliDoces.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Complement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cep = "12345-678",
                            Complement = "Kitnet",
                            Number = "4226",
                            Street = "Rua Mato Fino"
                        },
                        new
                        {
                            Id = 2,
                            Cep = "54321-876",
                            Complement = "",
                            Number = "9995",
                            Street = "Rua Floresta Grossa"
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Entities.CakeFlavor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CakeFlavors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chocolate",
                            Price = 30.00m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Morango",
                            Price = 35.00m
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomeId = 1,
                            Name = "Gustavo",
                            Phone = "(44) 91234-5678"
                        },
                        new
                        {
                            Id = 2,
                            HomeId = 2,
                            Name = "Lana",
                            Phone = "(44) 95555-4444"
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HomeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpf = "025.156.745-89",
                            Email = "edu@gmail.com",
                            HomeId = 2,
                            Name = "Eduardo",
                            Password = "123",
                            Phone = "(44) 91234-5678"
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AccomplishDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryAddressId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("DeliveryAddressId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IsabelliDoces.Entities.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CakeFlavorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CakeFlavorId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Entities.RoleContract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleContracts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            RoleId = 1,
                            StartDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Relations.DeliveryPlace", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddressId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ClientId", "AddressId");

                    b.HasIndex("AddressId");

                    b.ToTable("DeliveryPlaces");

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            AddressId = 1
                        },
                        new
                        {
                            ClientId = 1,
                            AddressId = 2
                        },
                        new
                        {
                            ClientId = 2,
                            AddressId = 1
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Relations.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PermissionType")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "PermissionType");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionType = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionType = 0
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionType = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionType = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionType = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionType = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionType = 4
                        });
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Client", b =>
                {
                    b.HasOne("IsabelliDoces.Entities.Address", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Employee", b =>
                {
                    b.HasOne("IsabelliDoces.Entities.Address", "Home")
                        .WithMany()
                        .HasForeignKey("HomeId");

                    b.Navigation("Home");
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Order", b =>
                {
                    b.HasOne("IsabelliDoces.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsabelliDoces.Entities.Address", "DeliveryAddress")
                        .WithMany()
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("DeliveryAddress");
                });

            modelBuilder.Entity("IsabelliDoces.Entities.OrderLine", b =>
                {
                    b.HasOne("IsabelliDoces.Entities.CakeFlavor", "CakeFlavor")
                        .WithMany()
                        .HasForeignKey("CakeFlavorId");

                    b.HasOne("IsabelliDoces.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("CakeFlavor");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("IsabelliDoces.Entities.RoleContract", b =>
                {
                    b.HasOne("IsabelliDoces.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsabelliDoces.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IsabelliDoces.Relations.DeliveryPlace", b =>
                {
                    b.HasOne("IsabelliDoces.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsabelliDoces.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("IsabelliDoces.Relations.RolePermission", b =>
                {
                    b.HasOne("IsabelliDoces.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IsabelliDoces.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
